"""Initial

Revision ID: 698d6d8a6cc2
Revises: 
Create Date: 2026-05-13 12:33:16.185634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '698d6d8a6cc2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_sessions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='session_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('director_phone', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('director_phone', name='uq_schools_director_phone')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'coordonnateur', 'enseignant', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('actif', 'inactif', name='user_status'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('classes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('planning_segments',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('jour', sa.Integer(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('classe', sa.String(length=50), nullable=True),
    sa.Column('matiere', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['program_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'jour', 'heure_debut', name='uq_planning_segment')
    )
    op.create_index(op.f('ix_planning_segments_session_id'), 'planning_segments', ['session_id'], unique=False)
    op.create_index(op.f('ix_planning_segments_teacher_id'), 'planning_segments', ['teacher_id'], unique=False)
    op.create_table('teacher_sessions',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['program_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'session_id')
    )
    op.create_table('seances',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('planning_segment_id', sa.UUID(), nullable=True),
    sa.Column('classe', sa.String(length=50), nullable=False),
    sa.Column('matiere', sa.String(length=100), nullable=True),
    sa.Column('date_seance', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('en_cours', 'terminee', 'annulee', name='seance_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('nb_eleves_presents', sa.Integer(), nullable=True),
    sa.Column('nb_eleves_total', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['planning_segment_id'], ['planning_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['program_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seances_session_id'), 'seances', ['session_id'], unique=False)
    op.create_index(op.f('ix_seances_teacher_id'), 'seances', ['teacher_id'], unique=False)
    op.create_table('rapports_prof',
    sa.Column('seance_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('difficultes', sa.Text(), nullable=True),
    sa.Column('points_positifs', sa.Text(), nullable=True),
    sa.Column('soumis_en_offline', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seance_id'], ['seances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rapports_prof_seance_id'), 'rapports_prof', ['seance_id'], unique=True)
    op.create_index(op.f('ix_rapports_prof_teacher_id'), 'rapports_prof', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rapports_prof_teacher_id'), table_name='rapports_prof')
    op.drop_index(op.f('ix_rapports_prof_seance_id'), table_name='rapports_prof')
    op.drop_table('rapports_prof')
    op.drop_index(op.f('ix_seances_teacher_id'), table_name='seances')
    op.drop_index(op.f('ix_seances_session_id'), table_name='seances')
    op.drop_table('seances')
    op.drop_table('teacher_sessions')
    op.drop_index(op.f('ix_planning_segments_teacher_id'), table_name='planning_segments')
    op.drop_index(op.f('ix_planning_segments_session_id'), table_name='planning_segments')
    op.drop_table('planning_segments')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('schools')
    op.drop_table('program_sessions')
    # ### end Alembic commands ###
