"""Add school_id to planning_segments

Revision ID: d2bfed0fb6d1
Revises: 698d6d8a6cc2
Create Date: 2026-05-13 13:16:56.931866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2bfed0fb6d1'
down_revision: Union[str, None] = '698d6d8a6cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planning_segments', sa.Column('school_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_planning_segments_school_id'), 'planning_segments', ['school_id'], unique=False)
    op.create_foreign_key(None, 'planning_segments', 'schools', ['school_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planning_segments', type_='foreignkey')
    op.drop_index(op.f('ix_planning_segments_school_id'), table_name='planning_segments')
    op.drop_column('planning_segments', 'school_id')
    # ### end Alembic commands ###
